import 'dart:ui';

class Constants {
  static const Color blueDark = Color.fromARGB(255, 86, 97, 123);

  static const String logoA = 'assets/images/logos/FIREPRIME_Logo_A.png';

  static const List<String> europeanCountries = [
    'albania',
    'andorra',
    'armenia',
    'austria',
    'azerbaijan',
    'belarus',
    'belgium',
    'bosniaHerzegovina',
    'bulgaria',
    'croatia',
    'cyprus',
    'czechia',
    'denmark',
    'estonia',
    'finland',
    'france',
    'georgia',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'ireland',
    'italy',
    'latvia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'malta',
    'moldova',
    'monaco',
    'montenegro',
    'netherlands',
    'northMacedonia',
    'norway',
    'poland',
    'portugal',
    'romania',
    'russia',
    'sanmarino',
    'serbia',
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
    'switzerland',
    'turkey',
    'ukraine',
    'unitedKingdom',
    'vaticanCity',
  ];

  static const Map<String, String> europeanCountriesCode = {
    "albania": "al",
    "andorra": "ad",
    "armenia": "am",
    "austria": "at",
    "azerbaijan": "az",
    "belarus": "by",
    "belgium": "be",
    "bosniaHerzegovina": "ba",
    "bulgaria": "bg",
    "croatia": "hr",
    "cyprus": "cy",
    "czechia": "cz",
    "denmark": "dk",
    "estonia": "ee",
    "finland": "fi",
    "france": "fr",
    "georgia": "ge",
    "germany": "de",
    "greece": "gr",
    "hungary": "hu",
    "iceland": "is",
    "ireland": "ie",
    "italy": "it",
    "latvia": "lv",
    "liechtenstein": "li",
    "lithuania": "lt",
    "luxembourg": "lu",
    "malta": "mt",
    "moldova": "md",
    "monaco": "mc",
    "montenegro": "me",
    "netherlands": "nl",
    "northMacedonia": "mk",
    "norway": "no",
    "poland": "pl",
    "portugal": "pt",
    "romania": "ro",
    "russia": "ru",
    "sanmarino": "sm",
    "serbia": "rs",
    "slovakia": "sk",
    "slovenia": "si",
    "spain": "es",
    "sweden": "se",
    "switzerland": "ch",
    "turkey": "tr",
    "ukraine": "ua",
    "unitedKingdom": "gb",
    "vaticanCity": "va",
  };
}
