import 'dart:ui';

class Constants {
  static const Color blueDark = Color.fromARGB(255, 86, 97, 123);

  static const String logoA = 'assets/images/logos/FIREPRIME_Logo_A.png';

  static const List<String> europeanCountries = [
    'albania',
    'andorra',
    'armenia',
    'austria',
    'azerbaijan',
    'belarus',
    'belgium',
    'bosniaHerzegovina',
    'bulgaria',
    'croatia',
    'cyprus',
    'czechia',
    'denmark',
    'estonia',
    'finland',
    'france',
    'georgia',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'ireland',
    'italy',
    'latvia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'malta',
    'moldova',
    'monaco',
    'montenegro',
    'netherlands',
    'northMacedonia',
    'norway',
    'poland',
    'portugal',
    'romania',
    'russia',
    'sanmarino',
    'serbia',
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
    'switzerland',
    'turkey',
    'ukraine',
    'unitedKingdom',
    'vaticanCity',
  ];
}
